install:
  - npm install
  - cd client && npm install && cd -
  - mv server/config.example.json server/config.json
before_script:
  - psql template1 -c 'create extension hstore;'
  - psql -c 'create database bucketly_test;' -U postgres
notifications:
  email: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
    - client/node_modules
