install:
  - npm install
  - cd client && npm install && cd -
  - npm install -g create-react-app react-scripts
  - mv server/config.example.json server/config.json
before_script:
  - psql -c 'create database bucketly_test;' -U postgres
  - psql -d postgres -U postgres -c 'CREATE EXTENSION hstore;'
notifications:
  email: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
    - client/node_modules
